### ISSUE TITLE
Commit version change 

### ISSUE THREAD

**Issue by martinklepsch** [degree9/boot-semver#17]
When using the version change in combination with the push tasks `ensure-clean` option you can't use. Both in the same boot invocation. To avoid this it might be handy to commit the version properties change as part of the version task.

**Comment by burn2delete** [comment]
Hey Martin,
I was thinking about this, maybe a check to see if the repo is already clean? If it is then commit the version change?

I noticed this also confused the git commit ID when the jar is built.

**Comment by martinklepsch** [comment]
> maybe a check to see if the repo is already clean?  

Yeah I guess that makes sense then you get clean, tagged, no-change release commits.

> I noticed this also confused the git commit ID when the jar is built.

How can it be confused if you're currently not making a commit? I don't think I understand :smile:

**Comment by burn2delete** [comment]
> How can it be confused if you're currently not making a commit?

I think this might be a problem in my workflow, not the task itself.

> Yeah I guess that makes sense then you get clean, tagged, no-change release commits.

Maybe boot.git should get a PR for write actions to the repo?

**Comment by burn2delete** [comment]
@martinklepsch this is possible with [boot-semgit](http://github.com/degree9/boot-semgit)
