### ISSUE TITLE
Change log generation

### ISSUE THREAD

**Issue by martinklepsch** [degree9/boot-semver#18]
Maybe out of scope: it would be nice to use git to generate a list of commits that went into the release. This could be prepended to a changes.md or similar. 

Given that this creates a dirty git state it will lead to similar problems as in #17. Maybe in that case users would have a `prep-release` type of task instead of a task that does all release steps.

**Comment by burn2delete** [comment]
@martinklepsch How does bootlaces update the readme and avoid the dirty state? I imagine we can do the same thing, actually would it be better to add this to bootlaces along side the update-readme task?

**Comment by burn2delete** [comment]
closing as out of scope for now.
