### ISSUE TITLE
Keep semver file wthin final jar

### ISSUE THREAD

**Issue by jgrzebyta** [degree9/boot-semver#27]
I found the final semver file is not kept within final jar - it is save in the project root directory and thus is not attached during building process. Do I miss another task or that is a feature?

**Comment by burn2delete** [comment]
This is correct, the `version.properties` file is kept in the root of the project and not included in the build.
May I ask your use case for including it in the final project jar?

**Comment by jgrzebyta** [comment]
First of all I would like to read version number (including commit number)
directly from the file rather than from pom.properties. I am not sure if
numbers further `build` should go to the pom. According to the semver
standard not. So that why. I would imagine it should be put to the version
file in a separate line.

**Comment by burn2delete** [comment]
This has been completed and will be included in the next version.

**Comment by burn2delete** [comment]
@jgrzebyta Version `1.3.0` is on clojars and includes this, next version will generate a namespace to use in projects which will have the version data.

**Comment by jgrzebyta** [comment]
Thanks for that!
