### ISSUE TITLE
Rename semver-git symbols

### ISSUE THREAD

**Issue by arichiardi** [degree9/boot-semver#39]
Hello again :smile: 

Given that I see folks (and myself) using `semver-short-git` more than `semver-git`, what about renaming them?

I propose:

`semver-short-git` -> `semver-git`
`semver-git` -> `semver-long-git`

And now that we are at it, we could rename them in `-commit` because I saw for instance that you want to read from a `tag` as well and the `-git` part could lose significance. The latter proposal of course depends on the future features so I might be missing something here.

Thank you!

**Comment by burn2delete** [comment]
It should really be moved to: https://github.com/degree9/boot-semgit

**Comment by arichiardi** [comment]
:smile: ... but now we need `semver` integration in `semgit`

**Comment by burn2delete** [comment]
Haha no I mean moved out of this package, and into that one. Semgit will soon have tasks for managing branching and other project related git tasks. I think it's a separation of concerns semver shouldn't care about the repo, that should be for another library.

**Comment by arichiardi** [comment]
Well, I like the fact that you can write the `version.properties` with a command and include it in the fileset. Maybe the two are not really overlapping that much...

**Comment by burn2delete** [comment]
this is included in master, also [boot-semgit](http://github.com/degree9/boot-semgit) is now available.

**Comment by arichiardi** [comment]
You mean the renaming? I cannot see it, which version?
