### ISSUE TITLE
Add guidance for users

### ISSUE THREAD

**Issue by jgrzebyta** [degree9/boot-semver#51]
In the mock project I attached previous time when I remove `:pre-release` setting boot still produces jar with the pre-release postfix. Also for example when I change `patch` setting to 'two the version become 0.0.2-SNAPSHOT. To have it working I need to remove `version.properties` file.

I am not sure if that is intentional or not. If so how should I make release commit?

**Comment by burn2delete** [comment]
When using the version task during development, add the `:develop true` option to the version task. This will prevent writing changes to the version.properties file.

**Comment by jgrzebyta** [comment]
Thus it seems that `:develop: true` is already set when `:pre-release` is `'snapshot' because I cannot make a release version from that. The other direction works. Am I right?

For example:
`0.0.1` -> `0.0.2-SNAPSHOT` works
`0.0.2-SNAPSHOT` -> `0.0.2` does not

**Comment by burn2delete** [comment]
develop must be true to prevent changes being saved to the version file. Release versions are the only way to properly update the version file.

Example: snapshot should never be written to the version file if you are using the develop option.
Only releases should modify the file.

**Comment by jgrzebyta** [comment]
Now I see.

So When I have a project I should set up for example (def version "0.1.16")
and add some task (or add extra command line setting) to build snapshot
version than? If I need to deploy that developing version I can do for
example:

```
boot dev build-standalone push --repo clojars
```

Is that right?

Can I change this issue title to `Add guidance for users`?

**Comment by burn2delete** [comment]
Correct!

Is there more detail I can add to the`:develop` documentation on the README?

**Comment by jgrzebyta** [comment]
I think the most important think is to add example of code for `build.boot` file.

**Comment by burn2delete** [comment]
There are code examples, is a part of the example not clear?
