### ISSUE TITLE
Add intertask communication

### ISSUE THREAD

**Issue by jgrzebyta** [degree9/boot-semver#52]
1. I miss kind of inter-tasks communication. Boot clj recommends using `fs` metadata.

So version task could also add version to the file-system metadata.

**Comment by jgrzebyta** [comment]
I found. I can use get-version.

**Comment by jgrzebyta** [comment]
I reopen because when I change version during compilation flow (e.g. add snapshot) than `get-version` is not able to find it and still use version from `.properties` file.

**Comment by burn2delete** [comment]
@jgrzebyta versions that depend on a runtime value cannot be updated during a build as this will cause pom task to be out of sync.

Please provide your build.boot file and I can modify the version options for you.

**Comment by jgrzebyta** [comment]
@flyboarder I will send build.boot file into email.

**Comment by jgrzebyta** [comment]
Solution found.
