### ISSUE TITLE
Deploy snapshot into clojars

### ISSUE THREAD

**Issue by jgrzebyta** [degree9/boot-semver#55]
What is a mock example to build and deploy `snapshot` pre-release jar.

The mock project does not work with compilation workflow `boot develop build-sources`. 
I expect jar file: `target/mock-issue-55-0.0.3-SNAPHOT-sources.jar` but I have `target/mock-issue-55-0.0.3-sources.jar` instead.

The mock project contains `/target` directory.

[mock-issue-55.tar.gz](https://github.com/degree9/boot-semver/files/971891/mock-issue-55.tar.gz)

**Comment by jgrzebyta** [comment]
Regarding #54

**Comment by burn2delete** [comment]
@jgrzebyta get-version is only for retrieving the static version within `version.properties`. It is unaware of pipeline state.

**Comment by jgrzebyta** [comment]
I found solution:in which version is encoded within fiteset metadata. 

```
(deftask encode-version
  "Look for version value inside namespace `version-ns` generated by boot-semver."
  [vn version-ns VER sym "Namespace with 'version value."]
  (let [version-ns (:version-ns *opts*)
        file-ns (str (clojure.string/join "/" (clojure.string/split
                                            (clojure.string/replace (str version-ns) #"-"
                                                                    "_") #"\.")) ".clj")
        project (str (name (get-env :project)))]
    (util/info "Load namespace %s\n" version-ns)
    (core/with-pre-wrap fs
      (load-file (-> (core/by-path (hash-set file-ns) (ls fs))
                     (first)
                     (core/tmp-file)
                     (.getCanonicalPath)))
      (core/commit! (with-meta fs {:version-sem (let [version-sem @(ns-resolve version-ns 'version)]
                                                  (util/info "Version : %s \n" version-sem)
                                                  version-sem)
                                   :project project})))))
```

**Comment by burn2delete** [comment]
What is your use case?

**Comment by jgrzebyta** [comment]
I updated the mock project the working workflows are:

```
boot [version|develop] build-sources
```
There are 2 optional options
 - `develop` produces `snapshot`
 - `version` produces the regular version

`build-soures` does the main job:
Beyond the normal work it:

  - encodes version and project name id file system metadata (task `encode-version`)
  - produces outcome jar file called `project.jar`
  - renames in an anonymous task the jar file according to metadata values.

The last issue which is pushing jar to *clojars*: The push task detects all the jar files and send them to external resources.

[mock-issue-55.tar.gz](https://github.com/degree9/boot-semver/files/978702/mock-issue-55.tar.gz)

**Comment by burn2delete** [comment]
Can you try version `1.5.0-SNAPSHOT` I am working with the clojars guys to fix continuous snapshot deployments.

There are new tasks used internally, such as `version-pom` and `version-push` which uses a new internal atom which contains the project version, additionally you can use the new `version` task after the watch command to update build version on each fileset change.

**Comment by burn2delete** [comment]
I would be interested in a PR for `version-fs`encoding the version to the fileset, or `version-env` syncing it with the environment map.

**Comment by burn2delete** [comment]
version `1.5.0` released

**Comment by burn2delete** [comment]
You can update your task to use the `degree9.boot-semver.impl/+version+` atom to get the current version.

Instead of the version in the generated namespace.
