### ISSUE TITLE
generated version keeping namespace is not in classpath

### ISSUE THREAD

**Issue by jgrzebyta** [degree9/boot-semver#60]
The generated version namespace is not available in the workflow classpath probably because is added into `resources` rather than `sources`.

**Comment by burn2delete** [comment]
resources is the correct type

**Comment by jgrzebyta** [comment]
I have problem with running unit tests because of error: `Could not locate rdf4j/version__init.class or rdf4j/version.clj on classpath.` 

I created a task `run-test`. In the main task I call sub task (`testing`) which adds directory `tests/` and file generated (by `version` command) `rdf4j.version` to classpath:

```
(deftask testing "Attach tests/ directory to classpath." []
  (comp
   (sift :to-source [#".*/rdfs4j/version\\.clj$"])
   (set-env! :source-paths #(conj % "tests"))))
```

It works if I remove the sift line and `(require '[rdf4j.version])` from all source but I need it because of option `-v` for return version number.

**Comment by jgrzebyta** [comment]
changes in boot would be helpful boot-clj/boot#617

**Comment by burn2delete** [comment]
Im not sure I completely understand the problem. However the `rdfs4j.version` namespace should be available to all the tasks that run after the version task. On each task run you will need to require the namespace.

**Comment by jgrzebyta** [comment]
I reproduced the issue in a [mock project](/jgrzebyta/mock-clojure).

command:
```
boot develop run-test
```

**Comment by jgrzebyta** [comment]
It is fixed. I found the problem is with testing function.
