### ISSUE TITLE
expose `get-version` in `boot.semver`

### ISSUE THREAD

**Issue by hkjels** [degree9/boot-semver#66]
I have a task that outputs documentation and it needs the version-number. ATM I have to include `boot.semver.impl` namespace for the `get-version` function. Would it not make sense to expose that function along with the rest of the public api?

**Comment by burn2delete** [comment]
Boot tasks aren't designed with public api's in mind, the task is itself the public api. `get-version` is part of the internals.

There will be a new version soon which stores the version in the boot env map, this map has a public accessor.
