### ISSUE TITLE
[Question] How can I parse a String variable with version  into boot-semver?

### ISSUE THREAD

**Issue by jgrzebyta** [degree9/boot-semver#70]
I need to add a singe variable with version number as a string.
How  can I import it into `boot-semer`? I am able to parse it into a map with string values: `{:major "0" :minor "2" ...}`. But that is not useful for `version` task from `boot-semver`. Do exist any workaround for that?

**Comment by burn2delete** [comment]
The correct way to do this would be to make your own task that parses the version string and then passes the parsed data to the semver version task.

**Comment by burn2delete** [comment]
Here is an example:
```
(deftask my-version 
"A custom version task."
[]
(let [{:keys [major minor patch]} (parse-version "1.2.3")]
  (semver/version :major major :minor minor :patch patch)))
```
